name: Build and Release Qt App

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:  # Allow manual dispatches

jobs:
  build_macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'

    - name: Build project (macOS)
      run: |
        qmake
        make -j$(sysctl -n hw.ncpu)

    - name: Create macOS installer
      run: |
        macdeployqt ./your-app-name.app
        hdiutil create -volname your-app-name -srcfolder ./your-app-name.app -ov -format UDZO your-app-name.dmg

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: your-app-name-macos.dmg
        path: your-app-name.dmg

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'

    - name: Build project (Windows)
      run: |
        qmake
        mingw32-make -j$(nproc)

    - name: Create Windows installer (NSIS)
      run: |
        makensis installer.nsi

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: your-app-name-windows.exe
        path: your-app-name.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_macos, build_windows]

    steps:
    - name: Download macOS installer
      uses: actions/download-artifact@v3
      with:
        name: your-app-name-macos.dmg

    - name: Download Windows installer
      uses: actions/download-artifact@v3
      with:
        name: your-app-name-windows.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          your-app-name-macos.dmg
          your-app-name-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
