name: Build and Release Qt App

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:  # Allow manual dispatches

jobs:
  build_macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize and update submodules

    - name: Set up Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'

    - name: Build project (macOS)
      run: |
        qmake
        make -j$(sysctl -n hw.ncpu)

    - name: List build directory contents
      run: ls *.app

    - name: Create macOS installer
      run: |
        macdeployqt ./BublesApp.app
        hdiutil create -volname BublesApp -srcfolder ./BublesApp.app -ov -format UDZO BublesApp.dmg

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: BublesApp.dmg
        path: BublesApp.dmg

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize and update submodules

    - name: Set up Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'

     - name: Install MinGW
      run: choco install mingw

    - name: Set PATH for MinGW
      run: |
        echo "##[add-path]C:\Program Files (x86)\mingw-w64\bin"

    - name: Build project (Windows)
      run: |
        qmake || { echo "qmake failed"; exit 1; }
        mingw32-make -j4

    - name: Create Windows installer (NSIS)
      run: |
        makensis installer.nsi

    - name: List build directory contents
      run: ls *.exe

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: BubblesApp.exe
        path: BublesApp.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_macos]

    steps:
    - name: Download macOS installer
      uses: actions/download-artifact@v3
      with:
        name: BubblesApp.dmg

    - name: Download Windows installer
      uses: actions/download-artifact@v3
      with:
        name: BubblesApp.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BubblesApp.dmg
          BubblesApp.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
