name: Build and Release Qt App

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:  # Allow manual dispatches

jobs:
  build_macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize and update submodules

    - name: Set up Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'

    - name: Build project (macOS)
      run: |
        qmake BublesApp.pro	
        make -j$(sysctl -n hw.ncpu)
  
   - name: List build directory contents
      run: ls -la ./build 

    - name: Create macOS installer
      run: |
        macdeployqt ./build/BublesApp.app
        hdiutil create -volname Bubbles -srcfolder ./build/BublesApp.app -ov -format UDZO BublesApp.dmg

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: bubbles.dmg
        path: BublesApp.dmg

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize and update submodules

    - name: Set up Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'

    - name: Build project (Windows)
      run: |
        qmake BublesApp.pro	
        mingw32-make -j$(nproc)

    - name: Create Windows installer (NSIS)
      run: |
        makensis installer.nsi

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: bubbles.exe
        path: ./build/BublesApp.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_macos, build_windows]

    steps:
    - name: Download macOS installer
      uses: actions/download-artifact@v3
      with:
        name: bubbles.dmg

    - name: Download Windows installer
      uses: actions/download-artifact@v3
      with:
        name: bubbles.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bubbles.dmg
          bubbles.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
